package io.github.sufarook.kiln.sample.shared

import app.cash.sqldelight.db.SqlDriver
import io.github.sufarook.kiln.runtime.eq
import io.github.sufarook.kiln.runtime.withTransaction
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine

/**
 * Demonstrates cross-table relationships using the generated `findBy<Parent>`,
 * `observeBy<Parent>`, and `deleteBy<Parent>` methods.
 */
class ProjectStore(driver: SqlDriver) {

    private val projectRepo = ProjectRepository(driver)
    private val taskRepo    = TaskRepository(driver)

    init {
        projectRepo.createTable()
        taskRepo.createTable()
    }

    // ── Projects ─────────────────────────────────────────────────────────────

    suspend fun createProject(name: String, description: String = ""): Project {
        val project = Project(name = name, description = description)
        projectRepo.insert(project)
        return projectRepo.findAll().last { it.name == name }
    }

    suspend fun allProjects(): List<Project> = projectRepo.findAll()

    // ── Tasks ─────────────────────────────────────────────────────────────────

    suspend fun addTask(title: String, projectId: Long): Task {
        val task = Task(title = title, projectId = projectId)
        taskRepo.insert(task)
        return taskRepo.findAll().last { it.title == title }
    }

    // Generated by @Relation — no boilerplate needed
    suspend fun tasksForProject(projectId: Long): List<Task> =
        taskRepo.findByProject(projectId)

    fun observeTasksForProject(projectId: Long): Flow<List<Task>> =
        taskRepo.observeByProject(projectId)

    suspend fun completeTask(task: Task) {
        taskRepo.update(task.copy(isDone = true))
    }

    suspend fun pendingTasksForProject(projectId: Long): List<Task> =
        taskRepo.findWhere { (TaskColumns.projectId eq projectId) and (TaskColumns.isDone eq false) }

    // ── Cascade delete — generated by @Relation(cascade = true) ──────────────

    suspend fun deleteProject(projectId: Long) {
        taskRepo.deleteByProject(projectId)   // cascade: remove children first
        projectRepo.delete(projectId)
    }

    // ── Reactive join — combines project + its tasks into one stream ──────────

    fun observeProjectWithTasks(projectId: Long): Flow<Pair<Project?, List<Task>>> =
        combine(
            projectRepo.observeAll(),
            taskRepo.observeByProject(projectId)
        ) { projects, tasks ->
            projects.find { it.id == projectId } to tasks
        }
}
