package com.farook.delightcrud.runtime

/**
 * Full description of one expected column, generated by the processor into each
 * repository's createTable() so SchemaMigrator can diff and migrate automatically.
 *
 * @param defaultValue  SQL literal for NOT NULL ALTER TABLE ADD COLUMN ("0", "0.0", "''", "X''").
 *                      Empty for nullable columns.
 * @param migrateFrom   Old column name when a property was renamed. Migrator copies
 *                      data from [migrateFrom] into [name] then drops the old column.
 * @param isPrimaryKey  True if this column is the primary key.
 * @param autoIncrement True if the PK is INTEGER PRIMARY KEY AUTOINCREMENT.
 * @param isUnique      True if the column has a UNIQUE constraint.
 */
data class ColumnDef(
    val name: String,
    val type: String,
    val nullable: Boolean,
    val defaultValue: String,
    val migrateFrom: String = "",
    val isPrimaryKey: Boolean = false,
    val autoIncrement: Boolean = false,
    val isUnique: Boolean = false
)
