plugins {
    alias(libs.plugins.kotlin.jvm)
    `java-gradle-plugin`
    alias(libs.plugins.vanniktech.publish)
    alias(libs.plugins.kover)
}

kotlin {
    // Pinned so published class-file version is reproducible. 17 is safe as a floor:
    // AGP 8.x already requires consumers to run Gradle on JDK 17+.
    jvmToolchain(17)
}

dependencies {
    implementation(gradleApi())
    // Ships KSP on the consumer's classpath so plugins.apply("com.google.devtools.ksp") works
    implementation(libs.ksp.gradle.plugin)
    // Consumer's build already has KGP — compile against it only
    compileOnly(kotlin("gradle-plugin"))

    testImplementation(gradleTestKit())
    testImplementation(libs.junit)
    // KilnPlugin only configures anything once a Kotlin plugin is applied, so the
    // tests need KGP on the classpath to exercise those callbacks at all.
    testImplementation(kotlin("gradle-plugin"))
}

/**
 * Generates `KilnBuildConfig` from the project's own group/version.
 *
 * The plugin has to embed the coordinates it resolves `annotations`, `runtime`,
 * and `processor` at. Hand-maintaining that as a constant meant it could drift
 * from the published version — it did, and 1.0.0-alpha01 shipped pointing at a
 * non-existent 1.0.0-SNAPSHOT. Deriving it here makes that drift impossible.
 */
val generateBuildConfig by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/kilnBuildConfig/kotlin")
    val pluginGroup = providers.provider { project.group.toString() }
    val pluginVersion = providers.provider { project.version.toString() }

    inputs.property("group", pluginGroup)
    inputs.property("version", pluginVersion)
    outputs.dir(outputDir)

    doLast {
        val pkgDir = outputDir.get().asFile.resolve("io/github/sufarook/kiln/gradle")
        pkgDir.mkdirs()
        pkgDir.resolve("KilnBuildConfig.kt").writeText(
            """
            // Generated by the :gradle-plugin build. Do not edit.
            package io.github.sufarook.kiln.gradle

            internal object KilnBuildConfig {
                const val GROUP = "${pluginGroup.get()}"
                const val VERSION = "${pluginVersion.get()}"
            }

            """.trimIndent()
        )
    }
}

kotlin.sourceSets.named("main") {
    kotlin.srcDir(generateBuildConfig)
}

gradlePlugin {
    plugins {
        create("kiln") {
            id = "io.github.sufarook.kiln"
            implementationClass = "io.github.sufarook.kiln.gradle.KilnPlugin"
            displayName = "Kiln"
            description = "Compile-time CRUD generation for Kotlin Multiplatform SQLite"
        }
    }
}

tasks.test {
    useJUnit()
    // Lets the suite assert the generated KilnBuildConfig matches what the build
    // actually publishes — the drift that shipped a broken 1.0.0-alpha01.
    systemProperty("kiln.expectedGroup", project.group.toString())
    systemProperty("kiln.expectedVersion", project.version.toString())
}

mavenPublishing {
    publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.CENTRAL_PORTAL)
    if (!System.getenv("ORG_GRADLE_PROJECT_signingInMemoryKey").isNullOrEmpty()) signAllPublications()

    coordinates(artifactId = "gradle-plugin")

    pom {
        name.set("Kiln Gradle Plugin")
        description.set("Gradle plugin for Kiln — one-line setup wires KSP, the processor, and generated sources into any KMP project.")
        url.set("https://github.com/sufarook/Kiln")
        licenses {
            license {
                name.set("Apache-2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0")
            }
        }
        developers {
            developer {
                id.set("sufarook")
                name.set("Syed Ummer Farook")
                email.set("syedfarook1798@gmail.com")
            }
        }
        scm {
            connection.set("scm:git:github.com/sufarook/Kiln.git")
            developerConnection.set("scm:git:ssh://github.com/sufarook/Kiln.git")
            url.set("https://github.com/sufarook/Kiln")
        }
    }
}
