package com.farook.krate.sample

import android.app.Application
import com.farook.krate.runtime.AndroidDatabaseDriverFactory

class SampleApplication : Application() {

    // Generated by Krate — available app-wide
    lateinit var todoRepo: TodoRepository
        private set

    override fun onCreate() {
        super.onCreate()
        val driver = AndroidDatabaseDriverFactory(this).create("todos.db")
        todoRepo = TodoRepository(driver)
        todoRepo.createTable()  // safe to call repeatedly — uses IF NOT EXISTS
    }
}
